# Team Deep Purple - Project Meta Jersey

# Site Settings
title: Meta Jersey
name: Team Deep Purple
email: notanemail@domain.com
description: Mapping the Metamorphical Changes within New Jersey
baseurl: /Meta-Jersey
url: pranavrele.github.io/Meta-Jersey

# Build Settings
markdown: kramdown
permalink: pretty

